config/routes.rb
Rails.application.routes.draw do
  root :to => 'portfolios#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :portfolios, :only => [:index]

  resources :admins, :only => [:index]

  resources :skills, :hobbies, :projects, :only => [:new, :create, :destroy, :edit, :update]

  post 'contact' => 'portfolios#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  has_one_attached :image
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :image
  validates :name, :presence => true
  validates :description, :presence => true
  validates :repo_link, :presence => true
  validates :deployment_link, :presence => true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_one_attached :image
  validates :name, :presence => true
  validates :experience, :presence => true
  validates :experience, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authorize_admin
  def index
    @title = "Admin Portal"
    @skills = Skill.all
    @hobbies = Hobby.all
    @projects = Project.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authorize_admin
    if !current_user || current_user.admin != true 
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :authorize_admin
  def new
    @hobby = Hobby.new
  end

  def create
    @hobby = Hobby.new(hobbies_params)
    if @hobby.save
      flash[:notice] = "Hobby successfully added."
      redirect_to admins_path
    else
      flash[:alert] = "Hobby was not saved, please check submission"
      redirect_to new_hobby_path
    end
  end

  def edit
    @hobby = Hobby.find(params[:id])
  end

  def update
    @hobby = Hobby.find(params[:id])
    if @hobby.update(hobbies_params)
      redirect_to admins_path
    else
      redirect_to edit_hobby_path(@hobby)
    end
  end

  def destroy
    @hobby = Hobby.find(params[:id])
    @hobby.destroy
    redirect_to admins_path
  end


private
  def hobbies_params
    params.require(:hobby).permit(:name, :description, :image)
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @title = "Nate Cottle"
    @subtitle = 'Junior Web Developer'
    @projects = Project.all
    @hobbies = Hobby.all
    @skills = Skill.all
  end

  def contact

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_admin
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project successfully added."
      redirect_to admins_path
    else
      flash[:alert] = "Project was not saved, please check submission"
      redirect_to new_project_path
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to admins_path
    else
      redirect_to edit_project_path(@project)
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admins_path
  end


private
  def project_params
    params.require(:project).permit(:name, :description, :repo_link, :deployment_link, :image)
  end


end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authorize_admin
  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skills_params)
    if @skill.save
      flash[:notice] = "Skill successfully added."
      redirect_to admins_path
    else
      flash[:alert] = "Skill was not saved, please check submission"
      redirect_to new_skill_path
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skills_params)
      redirect_to admins_path
    else
      redirect_to edit_skill_path(@skill)
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to admins_path
  end


private
  def skills_params
    params.require(:skill).permit(:name, :experience, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<div class="admin-info">
  <h2>Skills</h2>
  <table class='table'>
    <tr>
      <th>Name</th>
      <th>Years Experience</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @skills.each do |skill| %>
    <tr>
      <td><%= skill.name %></td>
      <td><%= skill.experience %></td>
      <td><span><%= link_to "Edit", edit_skill_path(skill), class: 'btn btn-warning' %></span></td>
      <td><span><%= link_to "Delete", skill_path(skill), :data => {:method => "delete"}, class: 'btn btn-danger' %></span></td>
    </tr>
    <% end %>
  </table>
  <h2>Hobbies</h2>
  <div class="cards-container">
    <% @hobbies.each do |hobby| %>
    <div class="card" style="width: 18rem;">
      <% if hobby.image.attached? %>
        <%= image_tag hobby.image, class: 'card-img-top'%>
      <%end%>
      <div class="card-body">
        <h5 class="card-title"><%= hobby.name %></h5>
        <p class="card-text"><%= hobby.description %></p>
        <span><%= link_to "Edit", edit_hobby_path(hobby), class: 'btn btn-warning' %></span>
        <span><%= link_to "Delete", hobby_path(hobby), :data => {:method => "delete"}, class: 'btn btn-danger' %></span>
      </div>
    </div>
    <% end %>
  </div>
  <h2>Projects</h2>
  <div class="cards-container">
    <% @projects.each do |project| %>
    <div class="card" style="width: 18rem;">
      <% if project.image.attached? %>
        <%= image_tag project.image, class: 'card-img-top'%>
      <%end%>
      <div class="card-body">
        <h5 class="card-title"><%= project.name %></h5>
        <p class="card-text"><%= project.description %></p>
        <p><%= link_to "Repository Link", project.repo_link %></p>
        <p><%= link_to "Deployed Project", project.deployment_link %></p>
        <span><%= link_to "Edit", edit_project_path(project), class: 'btn btn-warning' %></span>
        <span><%= link_to "Delete", project_path(project), :data => {:method => "delete"}, class: 'btn btn-danger' %></span>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/hobbies/_form.html.erb
<%= form_for @hobby do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Image" %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/hobbies/edit.html.erb
<div class="container">
  <h2>Update <%= @hobby.name %></h2>

  <%= render 'form' %>
</div>

app/views/hobbies/new.html.erb
<div class="container">
  <h2>Add a New Hobby</h2>

  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="jumbotron">
    <h1><%= @title %></h1>
    <h2><%= @subtitle %></h2>
  </div>
  <% if !current_user || current_user.admin == false %>
    <nav class="navbar fixed-bottom  navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if !current_user %>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, :data => { :method => 'delete'}, class: 'nav-link'%></li>
          <% end %>
        </ul>
      </div>
    </nav>
  <% elsif current_user.admin %>
    <nav class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", portfolios_path, class: 'nav-link' %>
           </li>
          <li class="nav-item">
            <%= link_to "Admin", admins_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "New Skill", new_skill_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "New Hobby", new_hobby_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "New Project", new_project_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, :data => { :method => 'delete'}, class: 'nav-link'%>
          </li>
        </ul>
      </div>
    </nav>
  <% end %>
  <body>
    <div class="alert">
      <%= flash[:alert] %>
    </div>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/portfolios/index.html.erb
<div class="portfolio">
  <div class="portfolio-body container">
    <h2 class="projects-heading">Projects</h2>
    <div class="projects">
      <div class="projects-body container">
        <div class="col">
          <div class="row row-flex">
            <% @projects.each do |project| %>
            <div class="card" style="width: 18rem;">
              <% if project.image.attached? %>
                <%= image_tag project.image, class: 'card-img-top'%>
              <%end%>
              <div class="card-body">
                <h5 class="card-title"><%= project.name %></h5>
                <p class="card-text"><%= project.description %></p>
                <p><%= link_to "Repository Link", project.repo_link %></p>
                <p><%= link_to "Deployed Project", project.deployment_link %></p>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <h2 class="about-heading">About Me</h2>
    <div class="about container">
      <h3 class="skills-header">Skills</h3>
      <div class="skills">
        <% @skills.each do |skill| %>
          <div class="card" style="width: 10rem;">
            <% if skill.image.attached? %>
              <%= image_tag skill.image, class:'skill-icon'%>
            <%end%>
            <p><%= skill.name %></p>
          </div>
        <% end %>
      </div>
      <div class="hobbies">
        <h3>Hobbies</h3>
        <div class="col">
          <div class="row row-flex">
            <% @hobbies.each do |hobby| %>
            <div class="card" style="width: 18rem;">
              <% if hobby.image.attached? %>
                <%= image_tag hobby.image, class: 'card-img-top'%>
              <%end%>
              <div class="card-body">
                <h5 class="card-title"><%= hobby.name %></h5>
                <p class="card-text"><%= hobby.description %></p>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="contact">
      <h2>Contact</h2>
      <div class="contact-info">
        <p>Nate Cottle</p>
        <p>cottle.nate@gmail.com</p>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :repo_link, "Repository Link" %>
    <%= f.text_field :repo_link, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :deployment_link, "Deployed Project Link" %>
    <%= f.text_field :deployment_link, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Image" %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <h2>Edit <%= @project.name %></h2>

  <%= render 'form' %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h2>Add a New Project</h2>

  <%= render 'form' %>
</div>

app/views/skills/_form.html.erb
<%= form_for @skill do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :experience, "Experience" %>
    <%= f.text_field :experience, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Skill Image" %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/skills/edit.html.erb
<div class="container">
  <h2>Update <%= @skill.name %></h2>

  <%= render 'form' %>
</div>

app/views/skills/new.html.erb
<div class="container">
  <h2>Add a New Skill</h2>

  <%= render 'form' %>
</div>